apiVersion: apps/v1
kind: Deployment
metadata:
  name: madhu-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: madhu-springboot
  template:
    metadata:
      labels:
        app: madhu-springboot
    spec:
      containers:
        - name: springboot
          image: madhuble01/docker-demo:docker-demo
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: madhu-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: madhu-springboot
